name: Auto Post to Instagram

on:
  schedule:
    - cron: '0 0,12 * * *'  # Runs at 6 AM and 6 PM IST (which is 12 AM and 12 PM UTC)
  workflow_dispatch:        # Allows manual triggering

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run auto_post script
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
      run: |
        python auto_post.py
