name: Auto Post to Instagram

on:
  schedule:
    - cron: '0 6 * * *'   # Every day at 6 AM UTC
    - cron: '0 18 * * *'  # Every day at 6 PM UTC
  workflow_dispatch:      # Manual trigger from GitHub Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          - name: Run auto_post script
          env:
            INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
            INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
          run: |
            python /home/runner/work/naturals-bot/naturals-bot/auto_post.py
        
